server:
  error:
    include-exception: true
    include-stacktrace: never
spring:
  profiles:
    active: local
#    active: dev
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/WEB-INF/views/
    suffix: .html
  devtools:
    livereload:
      enabled: true
    restart:
      log-condition-evaluation-delta: false
  messages:
    basename: static/messages/messages
    encoding: UTF-8
    cache-duration: 5
    fallback-to-system-locale: false

---
server:
  port: {local-port}
spring:
  profiles: local
logging:
  level:
    kr.co.kesti: debug
api:
  url: http://{host}:{port}
---
server:
  port: {dev-port}
spring:
  profiles: dev
logging:
  level:
    kr.co.kesti: info
api:
  url: http://{host}:{port}
---
server:
  port: {prd-port}
spring:
  profiles: prd
logging:
  level:
    kr.co.kesti: info
api:
  url: http://{host}:{port}